server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/retousuarios
    username: root
    password: 1701712480

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka