server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reto
    username: root
    password: 1701712480
  security:
    user:
      name: root
      password: s3cr3t

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8099/eureka
