
server:
  port: 8090

spring:
  application:
    name: users-service
  datasource:
    url: jdbc:mysql://localhost:3306/reto
    username: root
    password: 1701712480

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin1@localhost:8099/eureka/

appDescription: "Pragma Challenge"
appVersion: "1.0.0"

