server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reto
    username: root
    password: 1701712480

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/